### ISSUE TITLE
Inline help does not match CLI options

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-mgr#104]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

registry-mgr create-registry -help

I am getting the options:
  -index <name>        Elasticsearch index name. Default is 'registry'
  -shards <number>     Number of shards (partitions) for registry index. Default is 1
  -replicas <number>   Number of replicas (extra copies) of registry index. Default is 0

Which are not supported anymore.

### 🕵️ Expected behavior

I expected the inline help to be up to date.

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

On MacOs

### 📚 Version of Software Used

5.0.0

### 🦄 Related requirements

🦄 #xyz

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

They still exist and are used when using a direct connection rather than cognito.
