### ISSUE TITLE
Unable to update archive status of a lidvid in the registry

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-mgr#107]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I did update the status of lidvid `urn:nasa:pds:ladee_uvs::3.0` for displine node ATM on the production registry I am getting an error:

```
[itrejo@atmos2023 registry-manager-5.0.2]$ ./bin/registry-manager set-archive-status -auth /home/itrejo/.auth/registry-auth.txt -es file:///home/itrejo/.auth/atm_mcp_prod.xml -lidvid  urn:nasa:pds:ladee_uvs::3.0 -status archived
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See [http://www.slf4j.org/codes.html#StaticLoggerBinder](https://urldefense.us/v3/__http:/www.slf4j.org/codes.html*StaticLoggerBinder__;Iw!!PvBDto6Hs4WbVuu7!ICsYujAzASbHF0Sxyh8YQ1F14TdMatEyi_kLJX5wSItWHE4o1NV2s_xKsZB6lIT5_x9WLMzkeH6dip8qfOJuZ41_Yjw$) for further details.
[INFO] Setting product status. LIDVID =  urn:nasa:pds:ladee_uvs::3.0, status = archived
[ERROR] [ urn:nasa:pds:ladee_uvs::3.0]: document missing
```

@tloubrieu-jpl checked that the document exists in the atm-registry index.

### 🕵️ Expected behavior

I expected to be able to change the status.

### 📜 To Reproduce

Use authentication from atm node group and run registry-mgr as show above.

### 📚 Version of Software Used

registry-mgr 5.0.2

### 🦄 Related requirements

🦄 #xyz

**Comment by tloubrieu-jpl** [comment]
This is a one case that we are trying to reproduce an Engineering Node, it is critical for ATM node but this issue has not been encountered by other nodes so far.

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

I need the contents of `file:///home/itrejo/.auth/atm_mcp_prod.xml`.

**Comment by alexdunnjpl** [comment]
@al-niessner imho, logging into MCP Kion, opening the AWS web console, navigating to Amazon OpenSearch Service -> collections -> $collection -> OpenSearch Dashboards -> Interact with the OpenSearch API

That gets you a console with the ability to run raw requests like

```
GET /en-registry/_search?_source_includes=&size=0&track_total_hits=true
{
  "query": {
    "match_all": {}
  }
}

## urn:nasa:pds:cassini_iss_saturn:data_raw:1454725799n::1.0
GET /rms-registry/_doc/urn%3Anasa%3Apds%3Acassini_iss_saturn%3Adata_raw%3A1454725799n%3A%3A1.0
{
  "query": {
    "match_all": {}
  }
}


PUT /edunn-geo-registry
{
  "settings": {
    "number_of_shards": 2,
    "number_of_replicas": 0
  },
  "mappings": {
    "properties": {
      
    }
  }
}
```

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

I know this sounds crazy, but the double space after -lidvid in the command line might looks to being translated into the lidvid in the error message (the space after the '['). Please try it again with just 1 space after -lidvid.

**Comment by al-niessner** [comment]
Somehow somewhere a space is being prepended to the lidvid preventing it from being found. I need to work directly with the person who is having this problem because I cannot duplicate it.

**Comment by tloubrieu-jpl** [comment]
At a meeting with Irma we were unable to reproduce the bug. I am closing this issue.
