### ISSUE TITLE
registry-mgr return ERROR null

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-mgr#111]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

From In Sook Moon, PPI:

Harvest worked yesterday, but somehow today I got the following message today.
 

[SUMMARY] Reading configuration from /opt/pds/registry/harvest-4.0.4/./conf/ppi/vex-aspera4-els-pad.xml
[SUMMARY] Output directory: /tmp/harvest/out
[ERROR] null
 

I tried with another data bundle. 
 
Another issue with the registry 
 
./bin/registry-manager set-archive-status -auth /home/sysop/.auth/registry-auth.txt -es file:///home/sysop/config/ppi_mcp_prod.x ml -lidvid urn:nasa:pds:vex-aspera4-els::1.0 -status archived
 
[ERROR] null
 
 
Could you please explain what the problem is?
 

### 🕵️ Expected behavior

I expected the tool to work and change the archive status

### 📜 To Reproduce

1.
2.
3.
...

### 📚 Version of Software Used

harvest v4.0.4

### 🦄 Related requirements

🦄 #xyz

**Comment by tloubrieu-jpl** [comment]
For now, @al-niessner will add a stack trace instead of the null message. That will help to investigate that error in the future.

**Comment by c-suh** [comment]
@tloubrieu-jpl and @al-niessner please provide test data that previously triggered this null error, now replaced by a stacktrace. Ty.

**Comment by c-suh** [comment]
i&t.skip label added because we cannot reproduce this test case.
