### ISSUE TITLE
As a user, I want to update a bundle and associated collections' and products' archive status given a bundle lidvid

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-mgr#112]
## 💪 Motivation
...so that I can enable external access to the product metadata from the API.

## 📖 Additional Details

Sibling to NASA-PDS/registry-mgr#113 but for a bundle

## ⚖️ Acceptance Criteria
**Given**  a bundle or collection
**When I perform** a status update of the bundle or collection
**Then I expect**the bundle or collecrtion and all their embedded products to have their archive_status changed in opensearch

**Given**  an observational product
**When I perform** a status update of the product
**Then I expect**the product to have their archive_status changed in opensearch

**Comment by al-niessner** [comment]
@jordanpadams 

Requires four items:
1. add `--recurse` to update-status to identify when to walk the tree vs when not to
2. do we need to set levels? For instance, recurse 0 would do just bundle, recurse 1 would be bundle and collection, etc
3. do we follow references in products? Are we just walking the aggregate types (bundle and collection) but completing the entire set of references in a product then their references then their refen...
4. registry-mgr does not have any concept of products. All of the handling, parsing, etc has to be added. It can borrowed from validate or registry-api but it needs a very deep understanding of products, their types, and how references work. Do you want to borrow or just write a new trying to keep it minimal?

**Comment by c-suh** [comment]
@tloubrieu-jpl and @al-niessner for clarification, this (and for [#113](https://github.com/NASA-PDS/registry-mgr/issues/113)) is one directional, correct (i.e., top-down bundles to collections to products)? Meaning, for example, an archive status change to a product would not affect the archive status of its collection parent.

**Comment by c-suh** [comment]
@tloubrieu-jpl and @al-niessner how is this supposed to work with the VIDs? This is what I found (copy/pasting from issue that I started to draft):
> When I did `set-archive-status` on a bundle (i.e., LIDVID: urn:nasa:pds:mars2020.spice::3.0), I noticed that its children of lower VIDs and their children updated their archive status, but the child with the same VID (i.e., 3.0) and its children did not.

> I expected either all grand/children to update, regardless of VID, or only the same VID to update. I did not expect only lower VIDs to update.

Is this the expected behavior or a bug?

**Comment by tloubrieu-jpl** [comment]
Thanks @c-suh @al-niessner a user (@plawton-umd ) already reported this issue, see https://github.com/NASA-PDS/registry-mgr/issues/134
We will work on that in this build cycle.
