### ISSUE TITLE
Improve error message for corrupted registry_docs.json

### ISSUE THREAD

**Issue by pds-ops** [NASA-PDS/registry-mgr#43]
## 🐛 Describe the bug

Several users have noted a `[ERROR] null` coming from a registry manager execution with an invalid JSON. We should catch this error and report it more clearly to the user.

## 📜 To Reproduce
* See https://github.com/NASA-PDS/pds-registry-app/discussions/255
* Take any valid registry_docs.json, make it invalid JSON, and try to ingest with registry manager

## 🕵️ Expected behavior

More clear error message that the JSON is invalid, most likely due to a file system issue. Either direct the user to documentation for debugging (if it exists?), or just not they should re-run harvest.

## 🩺 Test Data / Additional context

Take any valid registry_docs.json, make it invalid JSON, and try to ingest with registry manager

**Comment by tdddblog** [comment]
The latest version of Harvest loads data directly into Elasticsearch. Temporary JSON data files are not generated anymore.
See

**Comment by jordanpadams** [comment]
per comment above, this has been closed.
