### ISSUE TITLE
bug with pagination limitations per OpenSearch config

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-mgr#53]
## 🐛 Describe the bug

A request with start parameter = 10000 and limit=500 returns an error 500.

Appplication log says:
`2022-07-19 22:21:45.796 ERROR 1 --- [p-nio-80-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is OpenSearchStatusException[OpenSearch exception [type=search_phase_execution_exception, reason=all shards failed]]; nested: OpenSearchException[OpenSearch exception [type=, reason=: Result window is too large, from + size must be less than or equal to: [10000] but was [10500]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]]; nested: OpenSearchException[OpenSearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10000] but was [10500]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]];] with root cause`

## 📜 To Reproduce
1. Launch request: 

curl --request GET 'https://pds.nasa.gov/api/search/1.0/products?q=pds:Identification_Area.pds:product_class eq "Product_Observational"&limit=500&fields=pds:Science_Facets.pds:discipline_name,lidvid,ops:Harvest_Info.ops:node_name&start=10000'

(url parameters need to be encoded)

2. Get error 500
3. See in registry-api logs:

`2022-07-19 22:21:45.796 ERROR 1 --- [p-nio-80-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is OpenSearchStatusException[OpenSearch exception [type=search_phase_execution_exception, reason=all shards failed]]; nested: OpenSearchException[OpenSearch exception [type=, reason=: Result window is too large, from + size must be less than or equal to: [10000] but was [10500]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]]; nested: OpenSearchException[OpenSearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10000] but was [10500]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]];] with root cause`

## 🕵️ Expected behavior

The size of the request is 500, we should not reach the limit given by opensearch.

## 📚 Version of Software Used

1.0.1

## 🖥 System Info

---

**Comment by al-niessner** [comment]
@jordanpadams @jimmie 

Why do we think this is the right place? I just did a 'find . -type f -exec grep opensearch {} \; -print'  and absolutely nothing appeared.

Whatever task/repo/SA/?? is resposible for starting opensearch needs to make this change. It does not appear to be this repo.

**Comment by jordanpadams** [comment]
@al-niessner I am fairly certain most things you can configure in opensearch and be configured via a config file we post when we setup the registry.

**Comment by jordanpadams** [comment]
@al-niessner maybe here?

**Comment by al-niessner** [comment]
> @al-niessner maybe here?
> 
> https://github.com/NASA-PDS/registry-mgr/blob/main/src/main/resources/elastic/registry.json

Nope. This is what gets indexed and has nothing to do with configuring opensearch at startup.
