### ISSUE TITLE
registry-mgr is not connecting to opensearch port 9200

### ISSUE THREAD

**Issue by gxtchen** [NASA-PDS/registry-mgr#67]
## 🐛 Describe the bug identified during I&T
I am following this instruction page to create registry and load test data, https://nasa-pds.github.io/registry/admin/create_reg.html#create-registry

I have try starting opensearch with the docker-compose.yml downloaded from opensearch website and using the registry docker
docker compose --profile=pds-core-registry up.

I am not able to get this command working "registry-manager create-registry" 

gxchen@RAYL-C01494 ~/pds/PDS4tools_current$ registry-manager create-registry -auth auth.cfg -shards 3 -replicas 1
[INFO] Creating index: registry
[INFO] Schema: /Users/gxchen/pds/PDS4tools/registry-manager/elastic/registry.json
[INFO] Shards: 3
[INFO] Replicas: 1
[ERROR] Connection is closed

my auth.cfg file:
# true - trust self-signed certificates; false - don't trust.
trust.self-signed = true
user = admin
password = admin

I was able to query the same image with the same port:
gxchen@RAYL-C01494 ~/pds/PDS4tools_current$ curl https://localhost:9200 -ku 'admin:admin'     
{
  "name" : "6fc260af7eb6",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "ULmH3joMQv2L3DSkpbchAg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.2.4",
    "build_type" : "tar",
    "build_hash" : "e505b10357c03ae8d26d675172402f2f2144ef0f",
    "build_date" : "2022-01-14T03:37:51.375300Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}

If this is a known issue, I wish it is clearly stated in the same document.
[registry-manager-docker-output.txt](https://github.com/NASA-PDS/registry-mgr/files/13111278/registry-manager-docker-output.txt)

**Comment by gxtchen** [comment]
this needs to be using https
registry-manager create-registry -es https://localhost:9200 -auth auth.cfg -shards 3 -replicas 1
and
https://localhost:9200/_cat/indices?v

please update that is the document https://nasa-pds.github.io/registry/admin/create_reg.html#create-registry

**Comment by tloubrieu-jpl** [comment]
Documentation still need to be updated.

**Comment by tloubrieu-jpl** [comment]
This bug is obsolete, since registry used OpenSearch serverless the connection configuration has been fully re-designed and re-developed. This ticket has no purpose in the latest version of registry-mgr.
