### ISSUE TITLE
As a user, I want to set archive-status using packageId

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-mgr#69]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Node Operator

### 💪 Motivation

...so that I can change the archive-status based upon package, not just lidvid

### Acceptance Criteria

**Given** harvest load and packageId
**When I perform** set archive-status using this packageId
**Then I expect** all products associated with that packageId to have their archive status changed. 

### ⚙️ Engineering Details

For some reason it was removed here: https://github.com/NASA-PDS/registry-mgr/commit/7e4025c0beb17698edcd00b885c4fe624d6e29b4#diff-ec88b907ad46507f1d6e2316a86761652fdc5e36ffab9c11640d65b3554e1daeL80, but NAIF needs it ASAP

**Comment by tloubrieu-jpl** [comment]
+1 , I need that now ! But I will extract the lidvid manually,
