### ISSUE TITLE
As a node person, I want to know all possible values for archive status

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/registry-mgr#71]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Node Operator

### 💪 Motivation

...so that the differences between the options and the access information is available.

### 📖 Additional Details

On the registry-manager GitHub documentation page and/or in the help option please include
- Is the product publicly available, only available to the responsible Node, or another (explained) list?
- The documentation states that staged is the setting at load.  Please provide information that would, for example, explain the difference(s) between staged and restricted or certified and archived.

### Acceptance Criteria

See documentation is updated with the applicable archive status values.

**Comment by tloubrieu-jpl** [comment]
Related note from @jordanpadams on slack:
Here are the terms: archived , staged, certified. There are tons of others possible
[5:33](https://jpl.slack.com/archives/DU7PQS6FP/p1705617209688699)
here are the old PDS3 values: https://pds.nasa.gov/datastandards/documents/im/v1/index_1L00.html#attribute_pds_data_set_pds3_pds_archive_status
[5:34](https://jpl.slack.com/archives/DU7PQS6FP/p1705617293982609)
we probably should have used a different term other than "archive status" for this registration/access status. But we have bigger fish to fry

**Comment by plawton-umd** [comment]
According to https://nasa-pds.github.io/registry/user/update_status.html#set-status, there are 4 term -  “archived”, “certified”, “restricted”, “staged”.  Only one of which is listed on PDS3 page linked to.  The information similar to the PDS3 page is not available on/from the update_status.html page.  Additional information about which terms make the products publicly available - or not - would be informative please.

**Comment by nutjob4life** [comment]
@tloubrieu-jpl working on making ideas clearer on this ticket; just needs to develop in order to get the list of authorized archive status and to raise an error when appropriate
